<a href="https://colab.research.google.com/github/AIAlchemy1/Recommendation_Systems_Portfolio/blob/main/03_Matrix_Factorization_SVD/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd

In [ ]:
# define a matrix that needs to be decomposed thru SVD
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# applying Singular-value decomposition
U, s, VT = svd(A)

In [ ]:
print(U)

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]


In [ ]:
print(s)

[1.68481034e+01 1.06836951e+00 3.33475287e-16]


In [ ]:
print(VT)

[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [ ]:
# create n x n Sigma matrix
Sigma = diag(s)

In [ ]:
print(Sigma)

[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]


In [ ]:
# reconstruct the matrix from u,s,vt
B = U.dot(Sigma.dot(VT))
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
